# Generated by Django 5.2.7 on 2025-10-15 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('instructor', models.CharField(max_length=150, verbose_name='Instructor Name')),
                ('category', models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('PHYSICS', 'Physics'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Course Category')),
                ('schedule', models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Schedule')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'indexes': [models.Index(fields=['name'], name='courses_name_dcd600_idx'), models.Index(fields=['category'], name='courses_categor_33f89e_idx'), models.Index(fields=['instructor'], name='courses_instruc_97576c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='Student ID')),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enrollment Date')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('FAILED', 'Failed')], default='ENROLLED', max_length=20, verbose_name='Enrollment Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Student Course Enrollment',
                'verbose_name_plural': 'Student Course Enrollments',
                'db_table': 'student_courses',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['student_id'], name='student_cou_student_f568d4_idx'), models.Index(fields=['course'], name='student_cou_course__96b3bd_idx'), models.Index(fields=['status'], name='student_cou_status_80cacb_idx')],
                'unique_together': {('student_id', 'course')},
            },
        ),
    ]
