# Generated by Django 5.2.7 on 2025-10-19 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_name_dcd600_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_categor_33f89e_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_instruc_97576c_idx',
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Attendance Percentage'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade out of 20', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('ENGINEERING', 'Engineering'), ('BUSINESS', 'Business'), ('ARTS', 'Arts'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Course Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Instructor Name'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student_id',
            field=models.IntegerField(help_text='ID of the student from Student Service', verbose_name='Student ID'),
        ),
    ]
