# Generated by Django 5.2.7 on 2025-11-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("student_id", models.IntegerField()),
                ("course_id", models.IntegerField()),
                ("enrollment_date", models.DateTimeField()),
                ("status", models.CharField(max_length=50)),
                (
                    "grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "student_courses",
                "managed": False,
            },
        ),
    ]
